version: "3"
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aprs_dev
