name = "aprsme"
version = "0.2.0"
description = "APRS packet display with type-safe Gleam modules"
licences = ["GPL-2.0"]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"