apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: aprs-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15 # Using a recent version
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: aprs_prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: aprs-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aprs-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
