apiVersion: v1
kind: Service
metadata:
  name: aprs-headless
  namespace: aprs
spec:
  clusterIP: None
  selector:
    app: aprs
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: dist
      port: 9000
      targetPort: 9000
