apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aprs
  namespace: aprs
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 0  # This ensures pods are only terminated after new ones are ready
  minReadySeconds: 30  # Wait 30 seconds after a pod is ready before considering the update successful