apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aprs
  namespace: aprs
spec:
  template:
    spec:
      containers:
      - name: aprs
        env:
        - name: DEPLOYED_AT
          value: "TIMESTAMP_PLACEHOLDER"