apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aprs
  namespace: aprs
spec:
  template:
    spec:
      containers:
      - name: aprs
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 12  # Gives 60 seconds total to start up