import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :aprsme, AprsmeWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  adapter: Bandit.PhoenixAdapter,
  http: [ip: {0, 0, 0, 0}, port: 4000]

# Runtime production configuration, including reading

config :esbuild,
  version: "0.17.11",
  default: [
    args: ~w(js/app.js --bundle --target=es2020 --outdir=../priv/static/assets --loader:.ts=ts),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

# Do not print debug messages in production
# of environment variables, is done on config/runtime.exs.
config :logger, level: :info

config :sentry,
  dsn: "https://40cd46881506a6c8e79ea353b62c2835@o4509627566063616.ingest.us.sentry.io/4509627568029696",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Configures Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req
