apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aprs-me
  namespace: flux-system
spec:
  interval: 1m
  url: https://git.mcintire.me/graham/aprs.me.git
  ref:
    branch: main
  secretRef:
    name: forgejo-git-credentials
