apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: aprs-me
  namespace: flux-system
spec:
  image: git.mcintire.me/graham/aprs.me
  interval: 1m
  secretRef:
    name: forgejo-registry
