apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: aprs-me
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: aprs-me
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      author:
        name: FluxCD
        email: fluxcd@aprs.me
      messageTemplate: 'chore: update aprs.me image to {{range .Changed.Changes}}{{.NewValue}}{{end}} [skip ci]'
  update:
    path: ./k8s
    strategy: Setters
